#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$SCRIPT_DIR/.."
if [ -f "$PROJECT_DIR/scripts/lib.sh" ]; then
  # shellcheck source=/dev/null
  source "$PROJECT_DIR/scripts/lib.sh"
fi

ICLOUD_DIR="$HOME/Library/Mobile Documents/com~apple~CloudDocs"
REPORT_TITLE="iCloud Quick Stats"

print_header() {
  printf "\n===== %s =====\n" "$1"
}

print_header "$REPORT_TITLE"
printf "Host: %s\n" "$(hostname)"
printf "Time: %s\n\n" "$(date -u +"%Y-%m-%d %H:%M:%S UTC")"

if [ ! -d "$ICLOUD_DIR" ]; then
  printf "iCloud Drive directory not found: %s\n" "$ICLOUD_DIR"
  exit 0
fi

# Total size (human)
print_header "Totals"
printf "iCloud root: %s\n" "$ICLOUD_DIR"
# macOS: use du -xhd 0 for directory size (if supported)
if du -xhd 0 "$ICLOUD_DIR" >/dev/null 2>&1; then
  du -xhd 0 "$ICLOUD_DIR" 2>/dev/null | awk '{print $1 "\t" $2}'
else
  du -sh "$ICLOUD_DIR" 2>/dev/null | awk '{print $1 "\t" $2}'
fi

# Counts
file_count=$(find "$ICLOUD_DIR" -type f 2>/dev/null | wc -l || true)
dir_count=$(find "$ICLOUD_DIR" -type d 2>/dev/null | wc -l || true)
printf "Files: %s\nDirectories: %s\n\n" "$file_count" "$dir_count"

# Top-level folder sizes
print_header "Top-level folders (sorted by size)"
# Try du -xhd 1, fall back to du -sh for each item
if du -xhd 1 "$ICLOUD_DIR" >/dev/null 2>&1; then
  du -xhd 1 "$ICLOUD_DIR" 2>/dev/null | sort -h | tail -n 20
else
  for p in "$ICLOUD_DIR"/*; do
    [ -e "$p" ] || continue
    du -sh "$p" 2>/dev/null || true
  done | sort -h | tail -n 20
fi

# Largest files
print_header "Largest files (>=100 MB)"
find "$ICLOUD_DIR" -type f -size +100M -print0 2>/dev/null | xargs -0 ls -lh 2>/dev/null | awk '{ print $5 "\t" $9 }' | sort -h | tail -n 50 || true

# Recently modified files (last 30 days)
print_header "Recently modified (last 30 days, top 50)"
find "$ICLOUD_DIR" -type f -mtime -30 -print0 2>/dev/null | xargs -0 ls -lt 2>/dev/null | head -n 50 || true

print_header "End of Report"
printf "Report generated by: scripts/quick_stats.sh\n\n"
